export const CLEAR_SECTION_DATA = 'CLEAR_SECTION_DATA'
export const SET_SECTION_DATA_SOURCE_END_POINT = 'SET_SECTION_DATA_SOURCE_END_POINT'
export const SET_LAST_RESPONSE_META = 'SET_LAST_RESPONSE_META'
export const UPDATE_SECTION_PARAMS = 'UPDATE_SECTION_PARAMS'

export const SET_SECTION_ITEMS = 'SET_SECTION_ITEMS'
export const SET_SECTION_LOADING_STATE = 'SET_SECTION_LOADING_STATE'

export const MERGE_ITEM_BY_ID = 'MERGE_ITEM_BY_ID'
export const SET_ITEM_BY_ID = 'SET_ITEM_BY_ID'
